# Generated by Django 4.1.7 on 2023-06-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_oder_id',
            new_name='razorpay_order_id',
        ),
    ]
